#ifndef PROJECT_CONF_H_
#define PROJECT_CONF_H_

#define WATCHDOG_CONF_ENABLE 0

#define UIP_CONF_BUFFER_SIZE 610
#define UIP_CONF_UDP_CONNS 1

#define DTLS_MAX_BUF 580

#define QUEUEBUF_CONF_NUM 9

#define LOG_CONF_LEVEL_RPL LOG_LEVEL_NONE
#define LOG_CONF_LEVEL_IPV6 LOG_LEVEL_NONE
#define LOG_CONF_LEVEL_6LOWPAN LOG_LEVEL_NONE
#define LOG_CONF_LEVEL_MAC LOG_LEVEL_NONE
#define LOG_LEVEL_DTLS LOG_LEVEL_NONE

#endif /* PROJECT_CONF_H_ */
