CONTIKI_PROJECT = ecb-test cbc-test ctr-test cbc-mac-test gcm-test ccm-test
CONTIKI_PROJECT += sha256-test ctr-state-test

all: $(CONTIKI_PROJECT)

PLATFORMS_ONLY = cc2538dk openmote-cc2538 zoul openmote-b

CONTIKI = ../../../..
include $(CONTIKI)/Makefile.include
